workflows:
  android-app:
    name: Build Android App
    max_build_duration: 20
    environment:
      android:
        ndk: r21d
      java: 17
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
